config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :companies do
    collection do
      get :pdf
      get :accounts
    end
  end
  resources :phones do
    collection do
      get :import
      post :import_excess
    end
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_many :phones, dependent: :destroy

  def self.import(phones_data, accounts_data)
    phones_data.drop(2).each do |row|
      name = row[11]
      # SBSゼンツウはマージ
      name = 'SBSゼンツウ株式会社' if name =~ /SBSゼンツウ/
      next if name =~ /SBS即配/
      next if row[5].to_i.zero? || row[16].blank?
      company = Company.find_or_initialize_by(name: name)
      company.save
    end
    accounts_data.drop(2).each do |row|
      name = row[0]
      # SBSゼンツウはマージ
      name = 'SBSゼンツウ株式会社' if name =~ /SBSゼンツウ/
      company = Company.find_by(name: name)
      next if company.blank?
      if row[16] == '〇'
        company.is_account_transfer = true
        company.transfer_description = row[13]
        company.payment_deadline = row[14]
        company.notice_to_transfer = row[15]
        company.save
      end
    end
  end

  def sum_of_charge
    sum_of_phone_price + sum_of_excess_charge + sum_of_option_price - sum_of_discount
  end

  def sum_of_phone_price
    phones.map(&:price).inject(:+) || 0
  end

  def sum_of_2gb
    phones.map do |phone|
      phone.price == 2980 ? 2980 : 0
    end.inject(:+) || 0
  end

  def sum_of_5gb
    phones.map do |phone|
      phone.price == 3980 ? 3980 : 0
    end.inject(:+) || 0
  end

  def num_of_2gb
    phones.to_a.count { |phone| phone.price == 2980 }
  end

  def num_of_5gb
    phones.to_a.count { |phone| phone.price == 3980 }
  end

  def sum_of_excess_charge
    sum_of_excess_charge_sms + sum_of_excess_charge_tel
  end

  def sum_of_excess_charge_sms
    phones.map(&:excess_charge_sms).inject(:+) || 0
  end

  def sum_of_excess_charge_tel
    phones.map(&:excess_charge_tel).inject(:+) || 0
  end

  def sum_of_discount
    phones.map(&:discount).inject(:+) || 0
  end

  def sum_of_option_price
    phones.map(&:option_price).inject(:+) || 0
  end

  def num_of_discount
    phones.to_a.count { |phone| phone.discount > 0 }
  end

  def num_of_option_price
    phones.to_a.count { |phone| phone.option_price > 0 }
  end

  def total_pages
    sliced_phones_array_for_invoice.length + 1
  end

  def sliced_phones_array_for_invoice
    items_number_of_first_page = (18 / number_of_price_items_per_phone).ceil
    items_per_page = (27 / number_of_price_items_per_phone).ceil
    top_phones = phones.take(items_number_of_first_page)
    left_phones = phones.drop(items_number_of_first_page)
                      .each_slice(items_per_page)
                      .to_a
    left_phones.unshift(top_phones)
  end

  def number_of_price_items_per_phone
    return 1 if phones.blank?
    phones.map do |phone|
      number_of_items = 1
      number_of_items += 1 if phone.option_price > 0
      number_of_items += 1 if phone.discount > 0
      number_of_items
    end.max
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'detail',                        # pdf ファイル名
               encording: 'UTF-8',                   # 日本語を使う場合には指定する
               layout: 'application.pdf.slim' # レイアウトファイルの指定
        # show_as_html: params[:debug].present? # debug するか？
      end
    end
  end

  def accounts
    respond_to do |format|
      format.html
      format.csv do
        @data = SheetRepository.accounts_data
        send_data render_to_string.gsub("\"\"",""), type: :csv
      end
    end
  end

  def pdf; end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit; end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to root_path, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to root_path, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to root_path, notice: 'Company was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def company_params
    params.fetch(:company, {})
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/views/companies/_form.html.slim
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      h2 = "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      ul
        - @company.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/companies/_invoice.html.slim
.wrapper.page-break.a4
  .content
    .alnright
      p
        = Date.current.strftime('%Y年%-m月%-d日')
    h1
      | 請求書
    .invoiceHead.clearfix
      .alpha
        .recipientNameBox
          p.recipientName style="font-size: #{company.name.length > 17 ? (19.5 * 17 / company.name.length) : 19.5}px"
            = "#{company.name} 御中"
          p
            | 毎度格別のお引き立てありがとうございます。<br>
              下記の通りご請求申し上げます。
          p
            = "ご請求期間: #{Date.current.next_month.beginning_of_month.strftime('%Y年%-m月%-d日')}〜#{Date.current.next_month.end_of_month.strftime('%Y年%-m月%-d日')}(末日締め)"
            <br>
            = "支払い条件: #{company.is_account_transfer ? company.transfer_description : "月末締め月末現金振込にて"}"

          p.subject
            |  件名：利用料金
        dl.totalAmountPrice.clearfix
          dt
            | ご請求金額
          dd
            = "¥" + company.sum_of_charge.tax_included.to_s(:delimited)
        div
          = "#{company.is_account_transfer ? "振替予定日: " + company.payment_deadline : "お支払い期限: " + Date.current.next_month.end_of_month.strftime('%Y年%-m月%-d日')}"

      .beta-gamma
        .beta.clearfix
          | SBSロジコム株式会社<br>
            営業本部 輸送営業開発部<br><br>
            東京都墨田区太平4-1-3<br>
            オリナスタワー10F<br>
            TEL 03-3829-3441<br>
            FAX 03-3829-2390
        .gamma
          = image_tag("seal.png")


    table.table_main[width="100%"]
      tbody
        tr
          th
            | 品名
          th[width="13%"]
            | 数量
          th[width="17%"]
            | 単価
          th[width="17%"]
            | 金額
        - if company.sum_of_2gb > 0
          tr
            td
              |  iGOQ端末レンタル料(2GB)
            td.alnright
              =  company.num_of_2gb
              span.unit-name
                | 台
            td.alnright
              =  "¥2,980"
            td.alnright
              =  "¥" + company.sum_of_2gb.to_s(:delimited)
        - if company.sum_of_5gb > 0
          tr
            td
              |  iGOQ端末レンタル料(5GB)
            td.alnright
              = company.num_of_5gb
              span.unit-name
                | 台
            td.alnright
              = "¥3,980"
            td.alnright
              = "¥" + company.sum_of_5gb.to_s(:delimited)
        - if company.sum_of_excess_charge > 0
          tr
            td
              = "別途有料使用分(#{Date.current.last_month.month}月分)"
            td.alnright
              span.unit-name
            td.alnright
            td.alnright
        - if company.sum_of_excess_charge_sms > 0
          tr
            td
              = "　通信料 メール(SMS)(YM/他社宛)"
            td.alnright
              span.unit-name
            td.alnright
              = "¥" + company.sum_of_excess_charge_sms.to_s(:delimited)
            td.alnright
              = "¥" + company.sum_of_excess_charge_sms.to_s(:delimited)
        - if company.sum_of_excess_charge_tel > 0
          tr
            td
              = "　通話料 通信サービス「0570等」"
            td.alnright
              span.unit-name
            td.alnright
              = "¥" + company.sum_of_excess_charge_tel.to_s(:delimited)
            td.alnright
              = "¥" + company.sum_of_excess_charge_tel.to_s(:delimited)
        - if company.sum_of_option_price > 0
          tr
            td
              = "オプション料金"
            td.alnright
              = company.num_of_option_price
              span.unit-name
                | 台
            td.alnright
            td.alnright
              = "¥" + company.sum_of_option_price.to_s(:delimited)
        - if company.sum_of_discount > 0
          tr
            td
              = "割引"
            td.alnright
              = company.num_of_discount
              span.unit-name
                | 台
            td.alnright
            td.alnright
              = "- ¥" + company.sum_of_discount.to_s(:delimited)
        tr
          td.blank
          td[colspan="2"]
            | 税別合計
          td.alnright
            = "¥" + company.sum_of_charge.to_s(:delimited)
        tr
          td.blank
          td[colspan="2"]
            | 消費税(8%)
          td.alnright
            = "¥" + company.sum_of_charge.tax.to_s(:delimited)
        tr
          td.blank
          td[colspan="2"]
            | 税込合計
          td.alnright
            = "¥" + company.sum_of_charge.tax_included.to_s(:delimited)

    p.bankAccount
      - if company.is_account_transfer
        = company.notice_to_transfer.html_safe
      - else
        | 下記口座にお振込くださいますよう、お願い申し上げます。<br>
          おそれ入りますが、振込手数料は貴社ご負担でよろしくお願いいたします。<br><br>
          銀行名:  三菱東京UFJ銀行<br>
          支店名:  振込第一支店<br>
          口座番号: 当座 6490156

  span.page-number
    = "1 / #{company.total_pages}"

- company.sliced_phones_array_for_invoice.each_with_index do |phones, index|
  .wrapper.page-break.a4.content
    - if index == 0
      .alnright
        p
          = Date.current.strftime('%Y年%-m月%-d日')
      h1
        | 内訳明細書
      .invoiceHead.clearfix
        .beta_gamma
          .beta.clearfix
            | SBSロジコム株式会社
    table.table_main[width="100%"]
      tbody
        tr
          th
            | 電話番号
          th
            | 料金内訳
          th
            | 金額
        - phones.each do |phone|
          tr
            td.alncenter
              = phone.number
            td.alnleft
              =  "iGOQ端末レンタル料(#{phone.price == 2980 ? "2GB" : "5GB"})"
            td.alnright
              =  "¥" + phone.price.to_s(:delimited)
          - if phone.excess_charge_sms > 0
            tr
              td
              td.alnleft
                = "#{Date.current.last_month.month}月分別途有料使用料 メール(SMS)(YM/他社宛)"
              td.alnright
                = "¥" + phone.excess_charge_sms.to_s(:delimited)
          - if phone.excess_charge_tel > 0
            tr
              td
              td.alnleft
                = "#{Date.current.last_month.month}月分別途有料使用料 通信サービス「0570等」"
              td.alnright
                = "¥" + phone.excess_charge_tel.to_s(:delimited)
          - if phone.option_price > 0
            tr
              td
              td.alnleft
                = "#{Date.current.next_month.month}月分オプション料金"
              td.alnright
                = "¥" + phone.option_price.to_s(:delimited)
          - if phone.discount > 0
            tr
              td
              td.alnleft
                = "#{Date.current.next_month.month}月分割引"
              td.alnright
                = "- ¥" + phone.discount.to_s(:delimited)
        - if index == company.total_pages - 2
          tr
            td.blank
            td
              | 税抜合計
            td.alnright
              = "¥" + company.sum_of_charge.to_s(:delimited)

    span.page-number
      = "#{index + 2} / #{company.total_pages}"

app/views/companies/_invoice.pdf.slim
.wrapper.page-break.a4
  .content
    .alnright
      p
        = Date.current.strftime('%Y年%-m月%-d日')
    h1
      | 請求書
    .invoiceHead.clearfix
      .alpha
        .recipientNameBox
          p.recipientName
            = "#{company.name} 御中"
          p
            | 毎度格別のお引き立てありがとうございます。<br>
              下記の通りご請求申し上げます。
          p
            = "ご請求期間: #{Date.current.next_month.beginning_of_month.strftime('%Y年%-m月%-d日')}〜#{Date.current.next_month.end_of_month.strftime('%Y年%-m月%-d日')}(末日締め)"
            <br>
            | 支払い条件: 月末締め月末現金振込にて<br>

          p.subject
            |  件名：利用料金
        dl.totalAmountPrice.clearfix
          dt
            | ご請求金額
          dd
            = "¥" + company.sum_of_charge.tax_included.to_s(:delimited)
        div
          = "お支払い期限: #{Date.current.next_month.end_of_month.strftime('%Y年%-m月%-d日')}"

      .beta-gamma
        .beta.clearfix
          | SBSロジコム株式会社<br>
            営業本部 輸送営業開発部<br><br>
            東京都墨田区太平4-1-3<br>
            オリナスタワー10F<br>
            TEL 03-3829-3441<br>
            FAX 03-3829-2390
        .gamma
          = wicked_pdf_image_tag("seal.png")


    table.table_main[width="100%"]
      tbody
        tr
          th
            | 品名
          th[width="13%"]
            | 数量
          th[width="12%"]
            | 単価
          th[width="15%"]
            | 金額
        tr
          td
            |  iGOQ端末レンタル料(2GB)
          td.alnright
            =  company.phones.size
            span.unit-name
              | 台
          td.alnright
            =  "¥" + company.phones.first.price.to_s(:delimited)
          td.alnright
            =  "¥" + company.sum_of_phone_price.to_s(:delimited)
        - if company.sum_of_excess_charge > 0
          tr
            td
              = "別途有料使用分(#{Date.current.last_month.month}月分)"
            td.alnright
              span.unit-name
            td.alnright
            td.alnright
        - if company.sum_of_excess_charge_sms > 0
          tr
            td
              = "　通信料 メール(SMS)(YM/他社宛)"
            td.alnright
              span.unit-name
            td.alnright
              = "¥" + company.sum_of_excess_charge_sms.to_s(:delimited)
            td.alnright
              = "¥" + company.sum_of_excess_charge_sms.to_s(:delimited)
        - if company.sum_of_excess_charge_tel > 0
          tr
            td
              = "　通話料 通信サービス「0570等」"
            td.alnright
              span.unit-name
            td.alnright
              = "¥" + company.sum_of_excess_charge_tel.to_s(:delimited)
            td.alnright
              = "¥" + company.sum_of_excess_charge_tel.to_s(:delimited)
        tr
          td.blank
          td[colspan="2"]
            | 税別合計
          td.alnright
            = "¥" + company.sum_of_charge.to_s(:delimited)
        tr
          td.blank
          td[colspan="2"]
            | 消費税(8%)
          td.alnright
            = "¥" + company.sum_of_charge.tax.to_s(:delimited)
        tr
          td.blank
          td[colspan="2"]
            | 税込合計
          td.alnright
            = "¥" + company.sum_of_charge.tax_included.to_s(:delimited)

    p.bankAccount
      | 下記口座にお振込くださいますよう、お願い申し上げます。<br>
        おそれ入りますが、振込手数料は貴社ご負担でよろしくお願いいたします。<br><br>
        銀行名:  三菱東京UFJ銀行<br>
        支店名:  振込第一支店<br>
        口座番号: 当座 6490156

  span.page-number
    = "1 / #{company.total_pages}"

- company.sliced_phones_array_for_invoice.each_with_index do |phones, index|
  .wrapper.page-break.a4.content
    - if index == 0
      .alnright
        p
          = Date.current.strftime('%Y年%-m月%-d日')
      h1
        | 内訳明細書
      .invoiceHead.clearfix
        .beta_gamma
          .beta.clearfix
            | SBSロジコム株式会社
    table.table_main[width="100%"]
      tbody
        tr
          th
            | 電話番号
          th
            | 料金内訳
          th
            | 金額
        - phones.each do |phone|
          tr
            td.alncenter
              = phone.number
            td.alnleft
              |  iGOQ端末レンタル料(2GB)
            td.alnright
              =  "¥" + phone.price.to_s(:delimited)
          - if phone.excess_charge_sms > 0
            tr
              td
              td.alnleft
                = "#{Date.current.last_month.month}月分別途有料使用料 メール(SMS)(YM/他社宛)"
              td.alnright
                = "¥" + phone.excess_charge_sms.to_s(:delimited)
          - if phone.excess_charge_tel > 0
            tr
              td
              td.alnleft
                = "#{Date.current.last_month.month}月分別途有料使用料 通信サービス「0570等」"
              td.alnright
                = "¥" + phone.excess_charge_tel.to_s(:delimited)
        - if index == company.total_pages - 2
          tr
            td.blank
            td
              | 税抜合計
            td.alnright
              = "¥" + company.sum_of_charge.to_s(:delimited)

    span.page-number
      = "#{index + 2} / #{company.total_pages}"

app/views/companies/edit.html.slim
h1 Editing company

== render 'form'

= link_to 'Show', @company
'  |
= link_to 'Back', companies_path

app/views/companies/pdf.html.slim
- Company.all.each do |company|
  - next if company.phones.blank?
  = render partial: 'invoice', locals:{ company: company }

app/views/companies/show.html.slim
= render partial: 'invoice', locals:{ company: @company }

app/views/companies/show.pdf.slim
= render partial: 'invoice', locals:{ company: @company }